# Generated by Django 3.1.4 on 2020-12-25 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0002_auto_20201225_1537'),
    ]

    operations = [
    ]
