# Generated by Django 3.1.4 on 2020-12-25 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0004_auto_20201225_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kategoriebazaru',
            old_name='title',
            new_name='nazev',
        ),
    ]
