# Generated by Django 3.1.4 on 2020-12-28 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0005_auto_20201225_1705'),
    ]

    operations = [
    ]
