# Generated by Django 3.1.4 on 2020-12-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0007_auto_20201228_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typinzeratu',
            name='nazev',
            field=models.CharField(choices=[('prodam', 'Prodám'), ('koupim', 'Koupím'), ('Other(Specify)', 'Other(Specify)')], max_length=200),
        ),
    ]
