# Generated by Django 3.1.4 on 2020-12-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0008_auto_20201228_1709'),
    ]

    operations = [
    ]
