# Generated by Django 3.1.4 on 2020-12-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0010_auto_20201228_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='polozkabazaru',
            name='telefon',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='typinzeratu',
            name='nazev',
            field=models.CharField(choices=[('prodam', 'Prodám'), ('koupim', 'Koupím')], max_length=200),
        ),
    ]
