# Generated by Django 3.1.4 on 2020-12-29 10:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazar', '0011_auto_20201228_1753'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PolozkaBazaru',
            new_name='Polozky',
        ),
    ]
