# Generated by Django 3.1.4 on 2021-01-01 16:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0012_auto_20201229_1149'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoriebazaru',
            options={'verbose_name': 'Kategorie bazaru', 'verbose_name_plural': 'Kategorie bazaru'},
        ),
        migrations.AlterModelOptions(
            name='polozky',
            options={'verbose_name': 'Inzerát', 'verbose_name_plural': 'Inzeráty'},
        ),
        migrations.AlterModelOptions(
            name='typinzeratu',
            options={'verbose_name': 'Typ inzerátu', 'verbose_name_plural': 'Typ inzerátu'},
        ),
        migrations.AddField(
            model_name='polozky',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='polozky',
            name='popis',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='typinzeratu',
            name='nazev',
            field=models.CharField(choices=[('Prodám', 'Prodám'), ('Koupím', 'Koupím')], max_length=200),
        ),
    ]
