# Generated by Django 3.1.4 on 2021-01-01 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazar', '0013_auto_20210101_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polozky',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='fotoinzerce/%Y/%m/%d'),
        ),
    ]
